### ISSUE TITLE
autoaccept, discord notifications

### ISSUE THREAD

**Issue by JJDee42** [0xM14N/rollhelper-extension#3]
hey, for longer time now discord notifications, and now even autoaccept seems to not work, while it worked perfectly fine, the notification one didnt work, then worked for like 2 days, and then didnt again, could there be any solution?

**Comment by JJDee42** [comment]
this is what it tells me in errors
Context
assets/popup/html/popup.html
Stack Trace
assets/popup/html/popup.html:0 (anonymous function)
Nothing to see here, move along.

**Comment by h4rder1** [comment]
hello, same issue here, pushover and discord notification are not working. what can we do?

**Comment by 0xM14N** [comment]
I will have a look at it and test, fix will be pushed after
