### ISSUE TITLE
Discord notifications not working

### ISSUE THREAD

**Issue by Paleva** [0xM14N/rollhelper-extension#5]
Im trying to use the discord webhook to send a notification to my discord server.

By default it didn't work

What I tried to fix it:
I have hardcoded my discord webhook link, changed it into an async function, but it still doesn't work.
Disabled adblockers on roll.

The stack trace:
TypeError: Failed to fetch
    at sendWebHookDiscord (sendDiscordWebhook.js:214:26)
    at socket.onmessage (rollhelper.js:202:8)
    
The error in console:
POST https://discord.com/api/webhooks/MYID/TOKEN
net::ERR_BLOCKED_BY_CLIENT

**Comment by 0xM14N** [comment]
Hey, are you using latest version? What browser are you using the extension on? Have you edited the discord payload?As far as I know there should not be any issues with dc notifs currently.

**Comment by Paleva** [comment]
Yes im using the latest version. Downloaded the new version today. Im using Version Version 130.0.6723.117 (Official Build) (64-bit) chrome

I have changed the sendDiscordWebhook into async function sendWebHookDiscord(urlDiscordWebhook, webhookType, tradeInfo) and pass the url as a string where it's called from.

This how the fetch block in the function looks. 
Haven't changed any of the templates.
 
```JS
params = templateWebhook[webhookType];
	try{
		const resposne = await fetch(url, {
			method: 'POST',
			headers: {
				'Content-Type': 'application/json',
			},
			body: JSON.stringify(params),
		})
		
		console.log(response.json())
		console.log("SENT TO DISCORD RAHHHHHHHHHHH")
	}
	catch(err){
		console.log(err);
		console.log("RAHHHHHHHHHHHHHHHHHHHHHHHHH");
	}	
```

I will try later with a fresh pull of the extension later. But this issue has been persistent for me with older versions as well.

**Comment by 0xM14N** [comment]
The function does not have to be async necessary, you also have small typo in your code at `const resposne` , also this POST request does not return any response body to `response.json()` as you do in your code. You can however check for status code (successful post is 204). I will add response check block and error catch block in next commit to make debugging easier.
Here is the example:
```javascript
let params = templateWebhook[webhookType];
	fetch(url, {
		method: 'POST',
		headers: {
			'Content-Type': 'application/json',
		},
		body: JSON.stringify(params),
	})
		.then(res => {
			if (res.status != 204){
			        // If the res.status is not 204, likely there are some issues with the request
				console.log(`res.status: ${res.status} | ${res.statusText}`)
				return;
			}
			console.log(`Discord webhook post successfull`)
	})
		.catch(err => console.log(err))
```
So far noone reported any issues with discord with latest version, it seems like the post request is somehow blocked on your side for some reason, Iam not sure why.

**Comment by Paleva** [comment]
Yeah most of the changes were made in desperation:D (and not being very familiar with webdev) but will try to figure out why it's being blocked...

**Comment by Paleva** [comment]
Found the solution! Privacy bagder (The extension) was messing with it possibly. After turning it off the webhook went thru fine.
Thanks for the help <3
